// Generated 11 Sep 2018 15:50 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Reports
{
	[Serializable]
	public class ReportInterventionNextStepList
	 : SingularBusinessListBase<ReportInterventionNextStepList, ReportInterventionNextStep>
	{
		#region " Business Methods "

		public ReportInterventionNextStep GetItem(int QuestionnaireAnswerResultID)
		{
			foreach (ReportInterventionNextStep child in this)
			{
				if (child.QuestionnaireAnswerResultID == QuestionnaireAnswerResultID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Report Intervention Next Steps";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{

			public int? QuestionnaireAnswerSetID = null;

			public int? QuestionnaireGroupID = null;

			public Criteria()
			{
			}

			public Criteria(int? questionnaireAnswerSetID, int? managementSphereID)
			{
				this.QuestionnaireAnswerSetID = questionnaireAnswerSetID;
				this.QuestionnaireGroupID = managementSphereID;
			}

		}

		public static ReportInterventionNextStepList NewReportInterventionNextStepList()
		{
			return new ReportInterventionNextStepList();
		}

		public ReportInterventionNextStepList()
		{
			// must have parameter-less constructor
		}

		public static ReportInterventionNextStepList GetReportInterventionNextStepList()
		{
			return DataPortal.Fetch<ReportInterventionNextStepList>(new Criteria());
		}

		public static ReportInterventionNextStepList GetReportInterventionNextStepList(int? QuestionnaireAnswerSetID, int? QuestionnaireGroupID)
		{
			return DataPortal.Fetch<ReportInterventionNextStepList>(new Criteria(QuestionnaireAnswerSetID, QuestionnaireGroupID));
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(ReportInterventionNextStep.GetReportInterventionNextStep(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getReportInterventionNextStepList";

						cm.Parameters.AddWithValue("@QuestionnaireAnswerSetID", Singular.Misc.NothingDBNull(crit.QuestionnaireAnswerSetID));
						cm.Parameters.AddWithValue("@QuestionnaireGroupID", Singular.Misc.NothingDBNull(crit.QuestionnaireGroupID));

						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}