// Generated 11 Sep 2018 08:20 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Reports
{
	[Serializable]
	public class ReportInterventionManagementSphereList
	 : METTBusinessListBase<ReportInterventionManagementSphereList, ReportInterventionManagementSphere>
	{
		#region " Business Methods "

		public ReportInterventionManagementSphere GetItem(int QuestionnaireAnswerResultID)
		{
			foreach (ReportInterventionManagementSphere child in this)
			{
				if (child.QuestionnaireAnswerResultID == QuestionnaireAnswerResultID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Report Intervention Management Spheres";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public int? QuestionnaireAnswerSetID = null;

			public int? ManagementSphereID = null;

			public Criteria()
			{
			}

			public Criteria(int? questionnaireAnswerSetID, int? managementSphereID)
			{
				this.QuestionnaireAnswerSetID = questionnaireAnswerSetID;
				this.ManagementSphereID = managementSphereID;
			}

		}

		public static ReportInterventionManagementSphereList NewReportInterventionManagementSphereList()
		{
			return new ReportInterventionManagementSphereList();
		}

		public ReportInterventionManagementSphereList()
		{
			// must have parameter-less constructor
		}

		public static ReportInterventionManagementSphereList GetReportInterventionManagementSphereList()
		{
			return DataPortal.Fetch<ReportInterventionManagementSphereList>(new Criteria());
		}

		public static ReportInterventionManagementSphereList GetReportInterventionManagementSphereList(int? QuestionnaireAnswerSetID, int? ManagementSphereID)
		{
			return DataPortal.Fetch<ReportInterventionManagementSphereList>(new Criteria(QuestionnaireAnswerSetID, ManagementSphereID));
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(ReportInterventionManagementSphere.GetReportInterventionManagementSphere(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getReportInterventionManagementSphereList";

						cm.Parameters.AddWithValue("@QuestionnaireAnswerSetID", Singular.Misc.NothingDBNull(crit.QuestionnaireAnswerSetID));
						cm.Parameters.AddWithValue("@ManagementSphereID", Singular.Misc.NothingDBNull(crit.ManagementSphereID));
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}