// Generated 11 Sep 2018 10:45 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Reports
{
	[Serializable]
	public class ROManagementSphere
	 : SingularReadOnlyBase<ROManagementSphere>
	{
		#region " Properties and Methods "

		#region " Properties "

		public static PropertyInfo<int> ManagementSphereIDProperty = RegisterProperty<int>(c => c.ManagementSphereID, "ID", 0);
		/// <summary>
		/// Gets the ID value
		/// </summary>
		[Display(AutoGenerateField = false), Key]
		public int ManagementSphereID
		{
			get { return GetProperty(ManagementSphereIDProperty); }
		}

		public static PropertyInfo<String> ManagementSphereProperty = RegisterProperty<String>(c => c.ManagementSphere, "Management Sphere", "");
		/// <summary>
		/// Gets the Management Sphere value
		/// </summary>
		[Display(Name = "Management Sphere", Description = "Title of Management Sphere as on Excel Summary Sheet")]
		public String ManagementSphere
		{
			get { return GetProperty(ManagementSphereProperty); }
		}

		public static PropertyInfo<String> ManagementSphereContentProperty = RegisterProperty<String>(c => c.ManagementSphereContent, "Management Sphere Content", "");
		/// <summary>
		/// Gets the Management Sphere Content value
		/// </summary>
		[Display(Name = "Management Sphere Content", Description = "Comprehensive Description of Management Sphere as on Excel Summary Sheet")]
		public String ManagementSphereContent
		{
			get { return GetProperty(ManagementSphereContentProperty); }
		}

		public static PropertyInfo<Boolean> IsActiveIndProperty = RegisterProperty<Boolean>(c => c.IsActiveInd, "Is Active", true);
		/// <summary>
		/// Gets the Is Active value
		/// </summary>
		[Display(Name = "Is Active", Description = "")]
		public Boolean IsActiveInd
		{
			get { return GetProperty(IsActiveIndProperty); }
		}

		public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
		/// <summary>
		/// Gets the Created By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int? CreatedBy
		{
			get { return GetProperty(CreatedByProperty); }
		}

		public static PropertyInfo<SmartDate> CreatedDateTimeProperty = RegisterProperty<SmartDate>(c => c.CreatedDateTime, "Created Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Created Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate CreatedDateTime
		{
			get { return GetProperty(CreatedDateTimeProperty); }
		}

		public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
		/// <summary>
		/// Gets the Modified By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int? ModifiedBy
		{
			get { return GetProperty(ModifiedByProperty); }
		}

		public static PropertyInfo<SmartDate> ModifiedDateTimeProperty = RegisterProperty<SmartDate>(c => c.ModifiedDateTime, "Modified Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Modified Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate ModifiedDateTime
		{
			get { return GetProperty(ModifiedDateTimeProperty); }
		}

		#endregion

		#region " Methods "

		protected override object GetIdValue()
		{
			return GetProperty(ManagementSphereIDProperty);
		}

		public override string ToString()
		{
			return this.ManagementSphere;
		}

		#endregion

		#endregion

		#region " Data Access & Factory Methods "

		internal static ROManagementSphere GetROManagementSphere(SafeDataReader dr)
		{
			var r = new ROManagementSphere();
			r.Fetch(dr);
			return r;
		}

		protected void Fetch(SafeDataReader sdr)
		{
			int i = 0;
			LoadProperty(ManagementSphereIDProperty, sdr.GetInt32(i++));
			LoadProperty(ManagementSphereProperty, sdr.GetString(i++));
			LoadProperty(ManagementSphereContentProperty, sdr.GetString(i++));
			LoadProperty(IsActiveIndProperty, sdr.GetBoolean(i++));
			LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
			LoadProperty(CreatedDateTimeProperty, sdr.GetSmartDate(i++));
			LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
			LoadProperty(ModifiedDateTimeProperty, sdr.GetSmartDate(i++));
		}

		#endregion

	}

}