// Generated 18 Jan 2021 13:22 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Categories
{
  [Serializable]
  public class SubCategoryList
   : MEBusinessListBase<SubCategoryList, SubCategory>
  {
    #region " Business Methods "

    public SubCategory GetItem(int SubCategoryID)
    {
      foreach (SubCategory child in this)
      {
        if (child.SubCategoryID == SubCategoryID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Sub Categorys";
    }

    #endregion

    #region " Data Access "

    public static SubCategoryList NewSubCategoryList()
    {
      return new SubCategoryList();
    }

    public SubCategoryList()
    {
      // must have parameter-less constructor
    }

    #endregion

  }

}