// Generated 22 Mar 2019 08:40 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class Designation
	 : METTBusinessBase<Designation>
	{
		#region " Properties and Methods "

		#region " Properties "

		public static PropertyInfo<int> DesignationIDProperty = RegisterProperty<int>(c => c.DesignationID, "ID", 0);
		/// <summary>
		/// Gets the ID value
		/// </summary>
		[Display(AutoGenerateField = false), Key]
		public int DesignationID
		{
			get { return GetProperty(DesignationIDProperty); }
		}

		public static PropertyInfo<String> DesignationProperty = RegisterProperty<String>(c => c.DesignationName, "Designation", "");
		/// <summary>
		/// Gets and sets the Designation value
		/// </summary>
		[Display(Name = "Designation", Description = "Description of Designation e.g. NationalPark, Ramsar, Marine"),
		StringLength(100, ErrorMessage = "Designation cannot be more than 100 characters")]
		public String DesignationName
		{
			get { return GetProperty(DesignationProperty); }
			set { SetProperty(DesignationProperty, value); }
		}

		public static PropertyInfo<Boolean> IsActiveIndProperty = RegisterProperty<Boolean>(c => c.IsActiveInd, "Is Active", true);
		/// <summary>
		/// Gets and sets the Is Active value
		/// </summary>
		[Display(Name = "Is Active", Description = ""),
		Required(ErrorMessage = "Is Active required")]
		public Boolean IsActiveInd
		{
			get { return GetProperty(IsActiveIndProperty); }
			set { SetProperty(IsActiveIndProperty, value); }
		}

		public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
		/// <summary>
		/// Gets the Created By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int CreatedBy
		{
			get { return GetProperty(CreatedByProperty); }
		}

		public static PropertyInfo<SmartDate> CreatedDateTimeProperty = RegisterProperty<SmartDate>(c => c.CreatedDateTime, "Created Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Created Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate CreatedDateTime
		{
			get { return GetProperty(CreatedDateTimeProperty); }
		}

		public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
		/// <summary>
		/// Gets the Modified By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int ModifiedBy
		{
			get { return GetProperty(ModifiedByProperty); }
		}

		public static PropertyInfo<SmartDate> ModifiedDateTimeProperty = RegisterProperty<SmartDate>(c => c.ModifiedDateTime, "Modified Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Modified Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate ModifiedDateTime
		{
			get { return GetProperty(ModifiedDateTimeProperty); }
		}

		#endregion

		#region " Methods "

		protected override object GetIdValue()
		{
			return GetProperty(DesignationIDProperty);
		}

		public override string ToString()
		{
			if (this.DesignationName.Length == 0)
			{
				if (this.IsNew)
				{
					return String.Format("New {0}", "Designation");
				}
				else
				{
					return String.Format("Blank {0}", "Designation");
				}
			}
			else
			{
				return this.DesignationName;
			}
		}

		#endregion

		#endregion

		#region " Validation Rules "

		protected override void AddBusinessRules()
		{
			base.AddBusinessRules();
		}

		#endregion

		#region " Data Access & Factory Methods "

		protected override void OnCreate()
		{
			// This is called when a new object is created
			// Set any variables here, not in the constructor or NewDesignation() method.
		}

		public static Designation NewDesignation()
		{
			return DataPortal.CreateChild<Designation>();
		}

		public Designation()
		{
			MarkAsChild();
		}

		internal static Designation GetDesignation(SafeDataReader dr)
		{
			var d = new Designation();
			d.Fetch(dr);
			return d;
		}

		protected void Fetch(SafeDataReader sdr)
		{
			using (BypassPropertyChecks)
			{
				int i = 0;
				LoadProperty(DesignationIDProperty, sdr.GetInt32(i++));
				LoadProperty(DesignationProperty, sdr.GetString(i++));
				LoadProperty(IsActiveIndProperty, sdr.GetBoolean(i++));
				LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
				LoadProperty(CreatedDateTimeProperty, sdr.GetSmartDate(i++));
				LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
				LoadProperty(ModifiedDateTimeProperty, sdr.GetSmartDate(i++));
			}

			MarkAsChild();
			MarkOld();
			BusinessRules.CheckRules();
		}

		protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
		{
			LoadProperty(ModifiedByProperty, Settings.CurrentUser.UserID);

			AddPrimaryKeyParam(cm, DesignationIDProperty);

			cm.Parameters.AddWithValue("@Designation", GetProperty(DesignationProperty));
			cm.Parameters.AddWithValue("@IsActiveInd", GetProperty(IsActiveIndProperty));
			cm.Parameters.AddWithValue("@ModifiedBy", GetProperty(ModifiedByProperty));

			return (scm) =>
			{
	// Post Save
	if (this.IsNew)
				{
					LoadProperty(DesignationIDProperty, scm.Parameters["@DesignationID"].Value);
				}
			};
		}

		protected override void SaveChildren()
		{
			// No Children
		}

		protected override void SetupDeleteCommand(SqlCommand cm)
		{
			cm.Parameters.AddWithValue("@DesignationID", GetProperty(DesignationIDProperty));
		}

		#endregion

	}

}