// Generated 22 Mar 2019 08:40 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class DesignationList
	 : METTBusinessListBase<DesignationList, Designation>
	{
		#region " Business Methods "

		public Designation GetItem(int DesignationID)
		{
			foreach (Designation child in this)
			{
				if (child.DesignationID == DesignationID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Designations";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static DesignationList NewDesignationList()
		{
			return new DesignationList();
		}

		public DesignationList()
		{
			// must have parameter-less constructor
		}

		public static DesignationList GetDesignationList()
		{
			return DataPortal.Fetch<DesignationList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(Designation.GetDesignation(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getDesignationList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}