// Generated 11 Jul 2018 12:07 - Singular Systems Object Generator Version 2.2.693
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class JobDescriptionList
	 : METTBusinessListBase<JobDescriptionList, JobDescription>
	{
		#region " Business Methods "

		public JobDescription GetItem(int JobDescriptionID)
		{
			foreach (JobDescription child in this)
			{
				if (child.JobDescriptionID == JobDescriptionID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Jobdescriptions";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static JobDescriptionList NewJobDescriptionList()
		{
			return new JobDescriptionList();
		}

		public JobDescriptionList()
		{
			// must have parameter-less constructor
		}

		public static JobDescriptionList GetJobDescriptionList()
		{
			return DataPortal.Fetch<JobDescriptionList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(JobDescription.GetJobDescription(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getJobDescriptionList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}