// Generated 11 Jul 2018 18:12 - Singular Systems Object Generator Version 2.2.693
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class LegaldesignationList
	 : METTBusinessListBase<LegaldesignationList, Legaldesignation>
	{
		#region " Business Methods "

		public Legaldesignation GetItem(int LegalDesignationID)
		{
			foreach (Legaldesignation child in this)
			{
				if (child.LegalDesignationID == LegalDesignationID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Legaldesignations";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static LegaldesignationList NewLegaldesignationList()
		{
			return new LegaldesignationList();
		}

		public LegaldesignationList()
		{
			// must have parameter-less constructor
		}

		public static LegaldesignationList GetLegaldesignationList()
		{
			return DataPortal.Fetch<LegaldesignationList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(Legaldesignation.GetLegaldesignation(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getLegaldesignationList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}