// Generated 11 Jul 2018 18:13 - Singular Systems Object Generator Version 2.2.693
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class NationalBiomeList
	 : METTBusinessListBase<NationalBiomeList, NationalBiome>
	{
		#region " Business Methods "

		public NationalBiome GetItem(int NationalBiomeID)
		{
			foreach (NationalBiome child in this)
			{
				if (child.NationalBiomeID == NationalBiomeID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Nationalbiomes";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static NationalBiomeList NewNationalBiomeList()
		{
			return new NationalBiomeList();
		}

		public NationalBiomeList()
		{
			// must have parameter-less constructor
		}

		public static NationalBiomeList GetNationalBiomeList()
		{
			return DataPortal.Fetch<NationalBiomeList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			while (sdr.Read())
			{
				this.Add(NationalBiome.GetNationalBiome(sdr));
			}
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getNationalBiomeList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}