// Generated 03 Apr 2019 11:33 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Maintenance
{
	[Serializable]
	public class QuestionnaireYear
	 : METTBusinessBase<QuestionnaireYear>
	{
		#region " Properties and Methods "

		#region " Properties "

		public static PropertyInfo<int> QuestionnaireYearIDProperty = RegisterProperty<int>(c => c.QuestionnaireYearID, "ID", 0);
		/// <summary>
		/// Gets the ID value
		/// </summary>
		[Display(AutoGenerateField = false), Key]
		public int QuestionnaireYearID
		{
			get { return GetProperty(QuestionnaireYearIDProperty); }
		}

		public static PropertyInfo<int> QuestionnaireYearProperty = RegisterProperty<int>(c => c.QuestionnaireYearName, "Questionnaire Year", 0);
		/// <summary>
		/// Gets and sets the Questionnaire Year value
		/// </summary>
		[Display(Name = "Questionnaire Year", Description = ""),
		Required(ErrorMessage = "Questionnaire Year required")]
		public int QuestionnaireYearName
		{
			get { return GetProperty(QuestionnaireYearProperty); }
			set { SetProperty(QuestionnaireYearProperty, value); }
		}

		public static PropertyInfo<Boolean> IsActiveIndProperty = RegisterProperty<Boolean>(c => c.IsActiveInd, "Is Active", true);
		/// <summary>
		/// Gets and sets the Is Active value
		/// </summary>
		[Display(Name = "Is Active", Description = "Field to indicate if the country record is active or not"),
		Required(ErrorMessage = "Is Active required")]
		public Boolean IsActiveInd
		{
			get { return GetProperty(IsActiveIndProperty); }
			set { SetProperty(IsActiveIndProperty, value); }
		}

		public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
		/// <summary>
		/// Gets the Created By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int CreatedBy
		{
			get { return GetProperty(CreatedByProperty); }
		}

		public static PropertyInfo<SmartDate> CreatedDateTimeProperty = RegisterProperty<SmartDate>(c => c.CreatedDateTime, "Created Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Created Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate CreatedDateTime
		{
			get { return GetProperty(CreatedDateTimeProperty); }
		}

		public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
		/// <summary>
		/// Gets the Modified By value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public int ModifiedBy
		{
			get { return GetProperty(ModifiedByProperty); }
		}

		public static PropertyInfo<SmartDate> ModifiedDateTimeProperty = RegisterProperty<SmartDate>(c => c.ModifiedDateTime, "Modified Date Time", new SmartDate(DateTime.Now));
		/// <summary>
		/// Gets the Modified Date Time value
		/// </summary>
		[Display(AutoGenerateField = false)]
		public SmartDate ModifiedDateTime
		{
			get { return GetProperty(ModifiedDateTimeProperty); }
		}

		#endregion

		#region " Methods "

		protected override object GetIdValue()
		{
			return GetProperty(QuestionnaireYearIDProperty);
		}

		public override string ToString()
		{
			if (this.CreatedDateTime.ToString().Length == 0)
			{
				if (this.IsNew)
				{
					return String.Format("New {0}", "Questionnaire Year");
				}
				else
				{
					return String.Format("Blank {0}", "Questionnaire Year");
				}
			}
			else
			{
				return this.CreatedDateTime.ToString();
			}
		}

		#endregion

		#endregion

		#region " Validation Rules "

		protected override void AddBusinessRules()
		{
			base.AddBusinessRules();
		}

		#endregion

		#region " Data Access & Factory Methods "

		protected override void OnCreate()
		{
			// This is called when a new object is created
			// Set any variables here, not in the constructor or NewQuestionnaireYear() method.
		}

		public static QuestionnaireYear NewQuestionnaireYear()
		{
			return DataPortal.CreateChild<QuestionnaireYear>();
		}

		public QuestionnaireYear()
		{
			MarkAsChild();
		}

		internal static QuestionnaireYear GetQuestionnaireYear(SafeDataReader dr)
		{
			var q = new QuestionnaireYear();
			q.Fetch(dr);
			return q;
		}

		protected void Fetch(SafeDataReader sdr)
		{
			using (BypassPropertyChecks)
			{
				int i = 0;
				LoadProperty(QuestionnaireYearIDProperty, sdr.GetInt32(i++));
				LoadProperty(QuestionnaireYearProperty, sdr.GetInt32(i++));
				LoadProperty(IsActiveIndProperty, sdr.GetBoolean(i++));
				LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
				LoadProperty(CreatedDateTimeProperty, sdr.GetSmartDate(i++));
				LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
				LoadProperty(ModifiedDateTimeProperty, sdr.GetSmartDate(i++));
			}

			MarkAsChild();
			MarkOld();
			BusinessRules.CheckRules();
		}

		protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
		{
			LoadProperty(ModifiedByProperty, Settings.CurrentUser.UserID);

			AddPrimaryKeyParam(cm, QuestionnaireYearIDProperty);

			cm.Parameters.AddWithValue("@QuestionnaireYear", GetProperty(QuestionnaireYearProperty));
			cm.Parameters.AddWithValue("@IsActiveInd", GetProperty(IsActiveIndProperty));
			cm.Parameters.AddWithValue("@ModifiedBy", GetProperty(ModifiedByProperty));

			return (scm) =>
			{
	// Post Save
	if (this.IsNew)
				{
					LoadProperty(QuestionnaireYearIDProperty, scm.Parameters["@QuestionnaireYearID"].Value);
				}
			};
		}

		protected override void SaveChildren()
		{
			// No Children
		}

		protected override void SetupDeleteCommand(SqlCommand cm)
		{
			cm.Parameters.AddWithValue("@QuestionnaireYearID", GetProperty(QuestionnaireYearIDProperty));
		}

		#endregion

	}

}