'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace CellFind

  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CellFind.ServiceSoap")> _
  Public Interface ServiceSoap

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogIn", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function LogIn(ByVal username As String, ByVal password As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogOut", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function LogOut(ByVal session_token As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSessionStatus", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSessionStatus(ByVal session_token As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSingleHLRLookupRequest", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSingleHLRLookupRequest(ByVal session_token As String, ByVal mobile As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendEmailMessage", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendEmailMessage(ByVal session_token As String, ByVal fromEmailAddress As String, ByVal toEmailAddress As String, ByVal subject As String, ByVal body As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingle", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingleRef", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingleRef(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal reference As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingleRefUP", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingleRefUP(ByVal username As String, ByVal password As String, ByVal mobile As String, ByVal message As String, ByVal reference As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingleBulkAcc", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingleBulkAcc(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingleHttpGet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingleHttpGet(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendSMSMessageSingleApp", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendSMSMessageSingleApp(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal application As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ScheduleSMSMessageSingle", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ScheduleSMSMessageSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ScheduleSMSMessageSingleHttpGet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ScheduleSMSMessageSingleHttpGet(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ScheduleSMSMessageSingleApp", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ScheduleSMSMessageSingleApp(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date, ByVal application As String) As Integer

    'CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BulkSMSFileUpload", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function BulkSMSFileUpload(ByVal request As CellFind.BulkSMSFileUploadRequest) As CellFind.BulkSMSFileUploadResponse

    'CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BulkSMSFileUploadScheduled", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function BulkSMSFileUploadScheduled(ByVal request As CellFind.BulkSMSFileUploadScheduledRequest) As CellFind.BulkSMSFileUploadScheduledResponse

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentSMSMessageDetailByID", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentSMSMessageDetailByID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentSMSMessageDetailByIDAll", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentSMSMessageDetailByIDAll(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentSMSMessages", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentSMSMessages(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentSMSMessagesForDateRange", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentSMSMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentSMSMessagesForDateRangeAdmin", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentSMSMessagesForDateRangeAdmin(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date, ByVal MSISDN As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessageDetailByID", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessageDetailByID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessageDetailByIDAll", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessageDetailByIDAll(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessages", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessages(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessagesForDateRange", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessagesForDateRangeAdmin", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessagesForDateRangeAdmin(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date, ByVal MSISDN As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetBulkMessageStatus", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetBulkMessageStatus(ByVal session_token As String, ByVal bulk_file_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetBulkMessageDetail", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetBulkMessageDetail(ByVal session_token As String, ByVal bulk_file_id As Integer, ByVal status_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSentMMSMessagesSearch", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetSentMMSMessagesSearch(ByVal session_token As String, ByVal search_for As String, ByVal value As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDeliveryReceipts", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetDeliveryReceipts(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateDeliveryPushedStatus", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function UpdateDeliveryPushedStatus(ByVal messageID As Integer) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetOutgoingMsgCountByUser1Month", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetOutgoingMsgCountByUser1Month(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendWAPPushSingle", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendWAPPushSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ScheduleWAPPushSingle", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ScheduleWAPPushSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer

    'CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BulkWAPPushFileUpload", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function BulkWAPPushFileUpload(ByVal request As CellFind.BulkWAPPushFileUploadRequest) As CellFind.BulkWAPPushFileUploadResponse

    'CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BulkWAPFileUploadScheduled", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function BulkWAPFileUploadScheduled(ByVal request As CellFind.BulkWAPFileUploadScheduledRequest) As CellFind.BulkWAPFileUploadScheduledResponse

    'CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BulkMMSFileUpload", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function BulkMMSFileUpload(ByVal request As CellFind.BulkMMSFileUploadRequest) As CellFind.BulkMMSFileUploadResponse

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RemoveLastUploadedMMSFile", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function RemoveLastUploadedMMSFile(ByVal fileName As String, ByVal sessionToken As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendMMSSingle", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendMMSSingle(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal recipients() As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendMMSSingleUploadFiles", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendMMSSingleUploadFiles(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal recipients() As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendMMSBulk", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendMMSBulk(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal bulkFileUploadID As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByUser", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByUser(ByVal session_token As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReplyMessagesByUser", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetReplyMessagesByUser(ByVal session_token As String) As String

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByUserDataSet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByUserDataSet(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByUserDataSetRef", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByUserDataSetRef(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessageCountByUser", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessageCountByUser(ByVal session_token As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessageCountByUserReplies", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessageCountByUserReplies(ByVal session_token As String) As Integer

    'CODEGEN: Generating message contract since the wrapper name (GetLastIncomingMessagesByUserDataSet) of message GetLastIncomingMessagesByUserDataSet does not match the default value (GetLastIncomingMessageByUserDataSet)
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetLastIncomingMessagesByUserDataSet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetLastIncomingMessageByUserDataSet(ByVal request As CellFind.GetLastIncomingMessagesByUserDataSet) As CellFind.GetLastIncomingMessagesByUserDataSet1

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUniqueOriginatorCountByShortCodeDataSet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetUniqueOriginatorCountByShortCodeDataSet(ByVal session_token As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReplyMessagesByUserDataSet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetReplyMessagesByUserDataSet(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReplyMessagesByUserDataSetOnce", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetReplyMessagesByUserDataSetOnce(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessageIDsByUserDataSet", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessageIDsByUserDataSet(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessageDetailByID", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessageDetailByID(ByVal session_token As String, ByVal reply_message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessageDetailByMessageID", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessageDetailByMessageID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByShortCode", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByShortCode(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByKeyword", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByKeyword(ByVal session_token As String, ByVal keyword As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesForDateRange", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_Date As Date, ByVal reported As Boolean) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByShortCodeOnce", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByShortCodeOnce(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByShortCodeOnceAdmin", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByShortCodeOnceAdmin(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByShortCodeAdminAcc", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByShortCodeAdminAcc(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AutoReplySendAlt", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function AutoReplySendAlt(ByVal session_token As String, ByVal reply_message_id As Integer, ByVal status As Boolean) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByKeywordCount", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByKeywordCount(ByVal session_token As String, ByVal keyword1 As String, ByVal keyword2 As String, ByVal keyword3 As String, ByVal searchOption As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncomingMessagesByKeywordCountDetail", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetIncomingMessagesByKeywordCountDetail(ByVal session_token As String, ByVal keyword1 As String, ByVal keyword2 As String, ByVal keyword3 As String, ByVal searchOption As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ExclusionsGetList", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ExclusionsGetList(ByVal session_token As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ExclusionsSearchList", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ExclusionsSearchList(ByVal session_token As String, ByVal recipient_no As String) As System.Data.DataSet

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ExclusionAddToAccount", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ExclusionAddToAccount(ByVal session_token As String, ByVal exclude_recipient As String) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ExclusionRemoveFromAccount", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function ExclusionRemoveFromAccount(ByVal session_token As String, ByVal exclusion_id As Integer) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCredits", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function GetCredits(ByVal session_token As String) As Integer

    'CODEGEN: Parameter 'SendOTASettingsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendOTASettings", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
    Function SendOTASettings(ByVal request As CellFind.SendOTASettingsRequest) As CellFind.SendOTASettingsResponse
  End Interface

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkSMSFileUpload", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkSMSFileUploadRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
    Public fileData() As Byte

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)> _
    Public fileName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)> _
    Public sessionToken As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String)
      MyBase.New()
      Me.fileData = fileData
      Me.fileName = fileName
      Me.sessionToken = sessionToken
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkSMSFileUploadResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkSMSFileUploadResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public BulkSMSFileUploadResult As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal BulkSMSFileUploadResult As String)
      MyBase.New()
      Me.BulkSMSFileUploadResult = BulkSMSFileUploadResult
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkSMSFileUploadScheduled", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkSMSFileUploadScheduledRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
    Public fileData() As Byte

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)> _
    Public fileName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)> _
    Public sessionToken As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)> _
    Public scheduleTime As Date

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduleTime As Date)
      MyBase.New()
      Me.fileData = fileData
      Me.fileName = fileName
      Me.sessionToken = sessionToken
      Me.scheduleTime = scheduleTime
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkSMSFileUploadScheduledResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkSMSFileUploadScheduledResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public BulkSMSFileUploadScheduledResult As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal BulkSMSFileUploadScheduledResult As String)
      MyBase.New()
      Me.BulkSMSFileUploadScheduledResult = BulkSMSFileUploadScheduledResult
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkWAPPushFileUpload", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkWAPPushFileUploadRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
    Public fileData() As Byte

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)> _
    Public fileName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)> _
    Public sessionToken As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String)
      MyBase.New()
      Me.fileData = fileData
      Me.fileName = fileName
      Me.sessionToken = sessionToken
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkWAPPushFileUploadResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkWAPPushFileUploadResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public BulkWAPPushFileUploadResult As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal BulkWAPPushFileUploadResult As String)
      MyBase.New()
      Me.BulkWAPPushFileUploadResult = BulkWAPPushFileUploadResult
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkWAPFileUploadScheduled", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkWAPFileUploadScheduledRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
    Public fileData() As Byte

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)> _
    Public fileName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)> _
    Public sessionToken As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)> _
    Public scheduleTime As Date

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduleTime As Date)
      MyBase.New()
      Me.fileData = fileData
      Me.fileName = fileName
      Me.sessionToken = sessionToken
      Me.scheduleTime = scheduleTime
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkWAPFileUploadScheduledResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkWAPFileUploadScheduledResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public BulkWAPFileUploadScheduledResult As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal BulkWAPFileUploadScheduledResult As String)
      MyBase.New()
      Me.BulkWAPFileUploadScheduledResult = BulkWAPFileUploadScheduledResult
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkMMSFileUpload", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkMMSFileUploadRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
    Public fileData() As Byte

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)> _
    Public fileName As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)> _
    Public sessionToken As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)> _
    Public scheduledDate As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduledDate As String)
      MyBase.New()
      Me.fileData = fileData
      Me.fileName = fileName
      Me.sessionToken = sessionToken
      Me.scheduledDate = scheduledDate
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="BulkMMSFileUploadResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class BulkMMSFileUploadResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public BulkMMSFileUploadResult As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal BulkMMSFileUploadResult As String)
      MyBase.New()
      Me.BulkMMSFileUploadResult = BulkMMSFileUploadResult
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="GetLastIncomingMessagesByUserDataSet", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class GetLastIncomingMessagesByUserDataSet

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public session_token As String

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal session_token As String)
      MyBase.New()
      Me.session_token = session_token
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="GetLastIncomingMessagesByUserDataSetResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class GetLastIncomingMessagesByUserDataSet1

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public GetLastIncomingMessagesByUserDataSetResult As System.Data.DataSet

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal GetLastIncomingMessagesByUserDataSetResult As System.Data.DataSet)
      MyBase.New()
      Me.GetLastIncomingMessagesByUserDataSetResult = GetLastIncomingMessagesByUserDataSetResult
    End Sub
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Partial Public Class OTAStruct
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged

    Private nAMEField As String

    Private aPNField As String

    Private bEARERField As BEARER

    Private pPP_AUTHNAMEField As String

    Private pPP_AUTHSECRETField As String

    Private pPP_AUTHTYPEField As PPP_AUTHTYPE

    Private pPP_LOGINTYPEField As PPP_LOGINTYPE

    Private pROXYField As String

    Private pORTField As PORT

    Private pROXY_LOGINTYPEField As PROXY_LOGINTYPE

    Private pROXY_AUTHNAMEField As String

    Private pROXY_AUTHSECRETField As String

    Private cSD_CALLTYPEField As CSD_CALLTYPE

    Private cSD_CALLSPEEDField As CSD_CALLSPEED

    Private cSD_DIALSTRINGField As String

    Private iSP_NAMEField As String

    Private sTATUSField As STATUS

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
    Public Property NAME() As String
      Get
        Return Me.nAMEField
      End Get
      Set(value As String)
        Me.nAMEField = value
        Me.RaisePropertyChanged("NAME")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
    Public Property APN() As String
      Get
        Return Me.aPNField
      End Get
      Set(value As String)
        Me.aPNField = value
        Me.RaisePropertyChanged("APN")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
    Public Property BEARER() As BEARER
      Get
        Return Me.bEARERField
      End Get
      Set(value As BEARER)
        Me.bEARERField = value
        Me.RaisePropertyChanged("BEARER")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
    Public Property PPP_AUTHNAME() As String
      Get
        Return Me.pPP_AUTHNAMEField
      End Get
      Set(value As String)
        Me.pPP_AUTHNAMEField = value
        Me.RaisePropertyChanged("PPP_AUTHNAME")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
    Public Property PPP_AUTHSECRET() As String
      Get
        Return Me.pPP_AUTHSECRETField
      End Get
      Set(value As String)
        Me.pPP_AUTHSECRETField = value
        Me.RaisePropertyChanged("PPP_AUTHSECRET")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=5)> _
    Public Property PPP_AUTHTYPE() As PPP_AUTHTYPE
      Get
        Return Me.pPP_AUTHTYPEField
      End Get
      Set(value As PPP_AUTHTYPE)
        Me.pPP_AUTHTYPEField = value
        Me.RaisePropertyChanged("PPP_AUTHTYPE")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=6)> _
    Public Property PPP_LOGINTYPE() As PPP_LOGINTYPE
      Get
        Return Me.pPP_LOGINTYPEField
      End Get
      Set(value As PPP_LOGINTYPE)
        Me.pPP_LOGINTYPEField = value
        Me.RaisePropertyChanged("PPP_LOGINTYPE")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=7)> _
    Public Property PROXY() As String
      Get
        Return Me.pROXYField
      End Get
      Set(value As String)
        Me.pROXYField = value
        Me.RaisePropertyChanged("PROXY")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=8)> _
    Public Property PORT() As PORT
      Get
        Return Me.pORTField
      End Get
      Set(value As PORT)
        Me.pORTField = value
        Me.RaisePropertyChanged("PORT")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=9)> _
    Public Property PROXY_LOGINTYPE() As PROXY_LOGINTYPE
      Get
        Return Me.pROXY_LOGINTYPEField
      End Get
      Set(value As PROXY_LOGINTYPE)
        Me.pROXY_LOGINTYPEField = value
        Me.RaisePropertyChanged("PROXY_LOGINTYPE")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=10)> _
    Public Property PROXY_AUTHNAME() As String
      Get
        Return Me.pROXY_AUTHNAMEField
      End Get
      Set(value As String)
        Me.pROXY_AUTHNAMEField = value
        Me.RaisePropertyChanged("PROXY_AUTHNAME")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=11)> _
    Public Property PROXY_AUTHSECRET() As String
      Get
        Return Me.pROXY_AUTHSECRETField
      End Get
      Set(value As String)
        Me.pROXY_AUTHSECRETField = value
        Me.RaisePropertyChanged("PROXY_AUTHSECRET")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=12)> _
    Public Property CSD_CALLTYPE() As CSD_CALLTYPE
      Get
        Return Me.cSD_CALLTYPEField
      End Get
      Set(value As CSD_CALLTYPE)
        Me.cSD_CALLTYPEField = value
        Me.RaisePropertyChanged("CSD_CALLTYPE")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=13)> _
    Public Property CSD_CALLSPEED() As CSD_CALLSPEED
      Get
        Return Me.cSD_CALLSPEEDField
      End Get
      Set(value As CSD_CALLSPEED)
        Me.cSD_CALLSPEEDField = value
        Me.RaisePropertyChanged("CSD_CALLSPEED")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=14)> _
    Public Property CSD_DIALSTRING() As String
      Get
        Return Me.cSD_DIALSTRINGField
      End Get
      Set(value As String)
        Me.cSD_DIALSTRINGField = value
        Me.RaisePropertyChanged("CSD_DIALSTRING")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=15)> _
    Public Property ISP_NAME() As String
      Get
        Return Me.iSP_NAMEField
      End Get
      Set(value As String)
        Me.iSP_NAMEField = value
        Me.RaisePropertyChanged("ISP_NAME")
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=16)> _
    Public Property STATUS() As STATUS
      Get
        Return Me.sTATUSField
      End Get
      Set(value As STATUS)
        Me.sTATUSField = value
        Me.RaisePropertyChanged("STATUS")
      End Set
    End Property

    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
      Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
      If (Not (propertyChanged) Is Nothing) Then
        propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
      End If
    End Sub
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum BEARER

    '''<remarks/>
    GSM_CSD

    '''<remarks/>
    GSM_SMS

    '''<remarks/>
    GSM_USSD

    '''<remarks/>
    IS_136_CSD

    '''<remarks/>
    GPRS
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum PPP_AUTHTYPE

    '''<remarks/>
    PAP

    '''<remarks/>
    CHAP

    '''<remarks/>
    MS_CHAP
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum PPP_LOGINTYPE

    '''<remarks/>
    AUTOMATIC

    '''<remarks/>
    MANUAL
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum PORT

    '''<remarks/>
    CONNECTIONLESS

    '''<remarks/>
    CONNECTIONORIENTED

    '''<remarks/>
    CONNECTIONLESSSECURE

    '''<remarks/>
    CONNECTIONORIENTEDSECURE
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum PROXY_LOGINTYPE

    '''<remarks/>
    AUTOMATIC

    '''<remarks/>
    MANUAL
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum CSD_CALLTYPE

    '''<remarks/>
    ANALOGUE

    '''<remarks/>
    ISDN
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum CSD_CALLSPEED

    '''<remarks/>
    [AUTO]
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")> _
  Public Enum STATUS

    '''<remarks/>
    OK

    '''<remarks/>
    FAILED
  End Enum

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="SendOTASettings", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class SendOTASettingsRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)> _
    Public sessionToken As String

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1), _
     System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)> _
    Public settings() As CellFind.OTAStruct

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal sessionToken As String, ByVal settings() As CellFind.OTAStruct)
      MyBase.New()
      Me.sessionToken = sessionToken
      Me.settings = settings
    End Sub
  End Class

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced), _
   System.ServiceModel.MessageContractAttribute(WrapperName:="SendOTASettingsResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
  Partial Public Class SendOTASettingsResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0), _
     System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)> _
    Public SendOTASettingsResult() As CellFind.OTAStruct

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal SendOTASettingsResult() As CellFind.OTAStruct)
      MyBase.New()
      Me.SendOTASettingsResult = SendOTASettingsResult
    End Sub
  End Class

  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
  Public Interface ServiceSoapChannel
    Inherits CellFind.ServiceSoap, System.ServiceModel.IClientChannel
  End Interface

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
  Partial Public Class ServiceSoapClient
    Inherits System.ServiceModel.ClientBase(Of CellFind.ServiceSoap)
    Implements CellFind.ServiceSoap

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
      MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
      MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
      MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
      MyBase.New(binding, remoteAddress)
    End Sub

    Public Function LogIn(ByVal username As String, ByVal password As String) As String Implements CellFind.ServiceSoap.LogIn
      Return MyBase.Channel.LogIn(username, password)
    End Function

    Public Function LogOut(ByVal session_token As String) As String Implements CellFind.ServiceSoap.LogOut
      Return MyBase.Channel.LogOut(session_token)
    End Function

    Public Function GetSessionStatus(ByVal session_token As String) As String Implements CellFind.ServiceSoap.GetSessionStatus
      Return MyBase.Channel.GetSessionStatus(session_token)
    End Function

    Public Function SendSingleHLRLookupRequest(ByVal session_token As String, ByVal mobile As String) As String Implements CellFind.ServiceSoap.SendSingleHLRLookupRequest
      Return MyBase.Channel.SendSingleHLRLookupRequest(session_token, mobile)
    End Function

    Public Function SendEmailMessage(ByVal session_token As String, ByVal fromEmailAddress As String, ByVal toEmailAddress As String, ByVal subject As String, ByVal body As String) As Integer Implements CellFind.ServiceSoap.SendEmailMessage
      Return MyBase.Channel.SendEmailMessage(session_token, fromEmailAddress, toEmailAddress, subject, body)
    End Function

    Public Function SendSMSMessageSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingle
      Return MyBase.Channel.SendSMSMessageSingle(session_token, mobile, message)
    End Function

    Public Function SendSMSMessageSingleRef(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal reference As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingleRef
      Return MyBase.Channel.SendSMSMessageSingleRef(session_token, mobile, message, reference)
    End Function

    Public Function SendSMSMessageSingleRefUP(ByVal username As String, ByVal password As String, ByVal mobile As String, ByVal message As String, ByVal reference As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingleRefUP
      Return MyBase.Channel.SendSMSMessageSingleRefUP(username, password, mobile, message, reference)
    End Function

    Public Function SendSMSMessageSingleBulkAcc(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingleBulkAcc
      Return MyBase.Channel.SendSMSMessageSingleBulkAcc(session_token, mobile, message)
    End Function

    Public Function SendSMSMessageSingleHttpGet(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingleHttpGet
      Return MyBase.Channel.SendSMSMessageSingleHttpGet(session_token, mobile, message)
    End Function

    Public Function SendSMSMessageSingleApp(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal application As String) As Integer Implements CellFind.ServiceSoap.SendSMSMessageSingleApp
      Return MyBase.Channel.SendSMSMessageSingleApp(session_token, mobile, message, application)
    End Function

    Public Function ScheduleSMSMessageSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer Implements CellFind.ServiceSoap.ScheduleSMSMessageSingle
      Return MyBase.Channel.ScheduleSMSMessageSingle(session_token, mobile, message, schedule_time)
    End Function

    Public Function ScheduleSMSMessageSingleHttpGet(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer Implements CellFind.ServiceSoap.ScheduleSMSMessageSingleHttpGet
      Return MyBase.Channel.ScheduleSMSMessageSingleHttpGet(session_token, mobile, message, schedule_time)
    End Function

    Public Function ScheduleSMSMessageSingleApp(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date, ByVal application As String) As Integer Implements CellFind.ServiceSoap.ScheduleSMSMessageSingleApp
      Return MyBase.Channel.ScheduleSMSMessageSingleApp(session_token, mobile, message, schedule_time, application)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_BulkSMSFileUpload(ByVal request As CellFind.BulkSMSFileUploadRequest) As CellFind.BulkSMSFileUploadResponse Implements CellFind.ServiceSoap.BulkSMSFileUpload
      Return MyBase.Channel.BulkSMSFileUpload(request)
    End Function

    Public Function BulkSMSFileUpload(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String) As String
      Dim inValue As CellFind.BulkSMSFileUploadRequest = New CellFind.BulkSMSFileUploadRequest()
      inValue.fileData = fileData
      inValue.fileName = fileName
      inValue.sessionToken = sessionToken
      Dim retVal As CellFind.BulkSMSFileUploadResponse = CType(Me, CellFind.ServiceSoap).BulkSMSFileUpload(inValue)
      Return retVal.BulkSMSFileUploadResult
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_BulkSMSFileUploadScheduled(ByVal request As CellFind.BulkSMSFileUploadScheduledRequest) As CellFind.BulkSMSFileUploadScheduledResponse Implements CellFind.ServiceSoap.BulkSMSFileUploadScheduled
      Return MyBase.Channel.BulkSMSFileUploadScheduled(request)
    End Function

    Public Function BulkSMSFileUploadScheduled(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduleTime As Date) As String
      Dim inValue As CellFind.BulkSMSFileUploadScheduledRequest = New CellFind.BulkSMSFileUploadScheduledRequest()
      inValue.fileData = fileData
      inValue.fileName = fileName
      inValue.sessionToken = sessionToken
      inValue.scheduleTime = scheduleTime
      Dim retVal As CellFind.BulkSMSFileUploadScheduledResponse = CType(Me, CellFind.ServiceSoap).BulkSMSFileUploadScheduled(inValue)
      Return retVal.BulkSMSFileUploadScheduledResult
    End Function

    Public Function GetSentSMSMessageDetailByID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentSMSMessageDetailByID
      Return MyBase.Channel.GetSentSMSMessageDetailByID(session_token, message_id)
    End Function

    Public Function GetSentSMSMessageDetailByIDAll(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentSMSMessageDetailByIDAll
      Return MyBase.Channel.GetSentSMSMessageDetailByIDAll(session_token, message_id)
    End Function

    Public Function GetSentSMSMessages(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentSMSMessages
      Return MyBase.Channel.GetSentSMSMessages(session_token)
    End Function

    Public Function GetSentSMSMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentSMSMessagesForDateRange
      Return MyBase.Channel.GetSentSMSMessagesForDateRange(session_token, from_date, to_date)
    End Function

    Public Function GetSentSMSMessagesForDateRangeAdmin(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date, ByVal MSISDN As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentSMSMessagesForDateRangeAdmin
      Return MyBase.Channel.GetSentSMSMessagesForDateRangeAdmin(session_token, from_date, to_date, MSISDN)
    End Function

    Public Function GetSentMMSMessageDetailByID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessageDetailByID
      Return MyBase.Channel.GetSentMMSMessageDetailByID(session_token, message_id)
    End Function

    Public Function GetSentMMSMessageDetailByIDAll(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessageDetailByIDAll
      Return MyBase.Channel.GetSentMMSMessageDetailByIDAll(session_token, message_id)
    End Function

    Public Function GetSentMMSMessages(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessages
      Return MyBase.Channel.GetSentMMSMessages(session_token)
    End Function

    Public Function GetSentMMSMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessagesForDateRange
      Return MyBase.Channel.GetSentMMSMessagesForDateRange(session_token, from_date, to_date)
    End Function

    Public Function GetSentMMSMessagesForDateRangeAdmin(ByVal session_token As String, ByVal from_date As Date, ByVal to_date As Date, ByVal MSISDN As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessagesForDateRangeAdmin
      Return MyBase.Channel.GetSentMMSMessagesForDateRangeAdmin(session_token, from_date, to_date, MSISDN)
    End Function

    Public Function GetBulkMessageStatus(ByVal session_token As String, ByVal bulk_file_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetBulkMessageStatus
      Return MyBase.Channel.GetBulkMessageStatus(session_token, bulk_file_id)
    End Function

    Public Function GetBulkMessageDetail(ByVal session_token As String, ByVal bulk_file_id As Integer, ByVal status_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetBulkMessageDetail
      Return MyBase.Channel.GetBulkMessageDetail(session_token, bulk_file_id, status_id)
    End Function

    Public Function GetSentMMSMessagesSearch(ByVal session_token As String, ByVal search_for As String, ByVal value As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetSentMMSMessagesSearch
      Return MyBase.Channel.GetSentMMSMessagesSearch(session_token, search_for, value)
    End Function

    Public Function GetDeliveryReceipts(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetDeliveryReceipts
      Return MyBase.Channel.GetDeliveryReceipts(session_token)
    End Function

    Public Function UpdateDeliveryPushedStatus(ByVal messageID As Integer) As Boolean Implements CellFind.ServiceSoap.UpdateDeliveryPushedStatus
      Return MyBase.Channel.UpdateDeliveryPushedStatus(messageID)
    End Function

    Public Function GetOutgoingMsgCountByUser1Month(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetOutgoingMsgCountByUser1Month
      Return MyBase.Channel.GetOutgoingMsgCountByUser1Month(session_token)
    End Function

    Public Function SendWAPPushSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String) As Integer Implements CellFind.ServiceSoap.SendWAPPushSingle
      Return MyBase.Channel.SendWAPPushSingle(session_token, mobile, message)
    End Function

    Public Function ScheduleWAPPushSingle(ByVal session_token As String, ByVal mobile As String, ByVal message As String, ByVal schedule_time As Date) As Integer Implements CellFind.ServiceSoap.ScheduleWAPPushSingle
      Return MyBase.Channel.ScheduleWAPPushSingle(session_token, mobile, message, schedule_time)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_BulkWAPPushFileUpload(ByVal request As CellFind.BulkWAPPushFileUploadRequest) As CellFind.BulkWAPPushFileUploadResponse Implements CellFind.ServiceSoap.BulkWAPPushFileUpload
      Return MyBase.Channel.BulkWAPPushFileUpload(request)
    End Function

    Public Function BulkWAPPushFileUpload(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String) As String
      Dim inValue As CellFind.BulkWAPPushFileUploadRequest = New CellFind.BulkWAPPushFileUploadRequest()
      inValue.fileData = fileData
      inValue.fileName = fileName
      inValue.sessionToken = sessionToken
      Dim retVal As CellFind.BulkWAPPushFileUploadResponse = CType(Me, CellFind.ServiceSoap).BulkWAPPushFileUpload(inValue)
      Return retVal.BulkWAPPushFileUploadResult
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_BulkWAPFileUploadScheduled(ByVal request As CellFind.BulkWAPFileUploadScheduledRequest) As CellFind.BulkWAPFileUploadScheduledResponse Implements CellFind.ServiceSoap.BulkWAPFileUploadScheduled
      Return MyBase.Channel.BulkWAPFileUploadScheduled(request)
    End Function

    Public Function BulkWAPFileUploadScheduled(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduleTime As Date) As String
      Dim inValue As CellFind.BulkWAPFileUploadScheduledRequest = New CellFind.BulkWAPFileUploadScheduledRequest()
      inValue.fileData = fileData
      inValue.fileName = fileName
      inValue.sessionToken = sessionToken
      inValue.scheduleTime = scheduleTime
      Dim retVal As CellFind.BulkWAPFileUploadScheduledResponse = CType(Me, CellFind.ServiceSoap).BulkWAPFileUploadScheduled(inValue)
      Return retVal.BulkWAPFileUploadScheduledResult
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_BulkMMSFileUpload(ByVal request As CellFind.BulkMMSFileUploadRequest) As CellFind.BulkMMSFileUploadResponse Implements CellFind.ServiceSoap.BulkMMSFileUpload
      Return MyBase.Channel.BulkMMSFileUpload(request)
    End Function

    Public Function BulkMMSFileUpload(ByVal fileData() As Byte, ByVal fileName As String, ByVal sessionToken As String, ByVal scheduledDate As String) As String
      Dim inValue As CellFind.BulkMMSFileUploadRequest = New CellFind.BulkMMSFileUploadRequest()
      inValue.fileData = fileData
      inValue.fileName = fileName
      inValue.sessionToken = sessionToken
      inValue.scheduledDate = scheduledDate
      Dim retVal As CellFind.BulkMMSFileUploadResponse = CType(Me, CellFind.ServiceSoap).BulkMMSFileUpload(inValue)
      Return retVal.BulkMMSFileUploadResult
    End Function

    Public Function RemoveLastUploadedMMSFile(ByVal fileName As String, ByVal sessionToken As String) As String Implements CellFind.ServiceSoap.RemoveLastUploadedMMSFile
      Return MyBase.Channel.RemoveLastUploadedMMSFile(fileName, sessionToken)
    End Function

    Public Function SendMMSSingle(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal recipients() As String) As String Implements CellFind.ServiceSoap.SendMMSSingle
      Return MyBase.Channel.SendMMSSingle(session_token, MMSDetail, SlideDetail, recipients)
    End Function

    Public Function SendMMSSingleUploadFiles(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal recipients() As String) As String Implements CellFind.ServiceSoap.SendMMSSingleUploadFiles
      Return MyBase.Channel.SendMMSSingleUploadFiles(session_token, MMSDetail, SlideDetail, recipients)
    End Function

    Public Function SendMMSBulk(ByVal session_token As String, ByVal MMSDetail As System.Data.DataTable, ByVal SlideDetail As System.Data.DataTable, ByVal bulkFileUploadID As String) As String Implements CellFind.ServiceSoap.SendMMSBulk
      Return MyBase.Channel.SendMMSBulk(session_token, MMSDetail, SlideDetail, bulkFileUploadID)
    End Function

    Public Function GetIncomingMessagesByUser(ByVal session_token As String) As String Implements CellFind.ServiceSoap.GetIncomingMessagesByUser
      Return MyBase.Channel.GetIncomingMessagesByUser(session_token)
    End Function

    Public Function GetReplyMessagesByUser(ByVal session_token As String) As String Implements CellFind.ServiceSoap.GetReplyMessagesByUser
      Return MyBase.Channel.GetReplyMessagesByUser(session_token)
    End Function

    Public Function GetIncomingMessagesByUserDataSet(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByUserDataSet
      Return MyBase.Channel.GetIncomingMessagesByUserDataSet(session_token)
    End Function

    Public Function GetIncomingMessagesByUserDataSetRef(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByUserDataSetRef
      Return MyBase.Channel.GetIncomingMessagesByUserDataSetRef(session_token)
    End Function

    Public Function GetIncomingMessageCountByUser(ByVal session_token As String) As Integer Implements CellFind.ServiceSoap.GetIncomingMessageCountByUser
      Return MyBase.Channel.GetIncomingMessageCountByUser(session_token)
    End Function

    Public Function GetIncomingMessageCountByUserReplies(ByVal session_token As String) As Integer Implements CellFind.ServiceSoap.GetIncomingMessageCountByUserReplies
      Return MyBase.Channel.GetIncomingMessageCountByUserReplies(session_token)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_GetLastIncomingMessageByUserDataSet(ByVal request As CellFind.GetLastIncomingMessagesByUserDataSet) As CellFind.GetLastIncomingMessagesByUserDataSet1 Implements CellFind.ServiceSoap.GetLastIncomingMessageByUserDataSet
      Return MyBase.Channel.GetLastIncomingMessageByUserDataSet(request)
    End Function

    Public Function GetLastIncomingMessageByUserDataSet(ByVal session_token As String) As System.Data.DataSet
      Dim inValue As CellFind.GetLastIncomingMessagesByUserDataSet = New CellFind.GetLastIncomingMessagesByUserDataSet()
      inValue.session_token = session_token
      Dim retVal As CellFind.GetLastIncomingMessagesByUserDataSet1 = CType(Me, CellFind.ServiceSoap).GetLastIncomingMessageByUserDataSet(inValue)
      Return retVal.GetLastIncomingMessagesByUserDataSetResult
    End Function

    Public Function GetUniqueOriginatorCountByShortCodeDataSet(ByVal session_token As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet Implements CellFind.ServiceSoap.GetUniqueOriginatorCountByShortCodeDataSet
      Return MyBase.Channel.GetUniqueOriginatorCountByShortCodeDataSet(session_token, from_date, to_Date)
    End Function

    Public Function GetReplyMessagesByUserDataSet(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetReplyMessagesByUserDataSet
      Return MyBase.Channel.GetReplyMessagesByUserDataSet(session_token)
    End Function

    Public Function GetReplyMessagesByUserDataSetOnce(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetReplyMessagesByUserDataSetOnce
      Return MyBase.Channel.GetReplyMessagesByUserDataSetOnce(session_token)
    End Function

    Public Function GetIncomingMessageIDsByUserDataSet(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessageIDsByUserDataSet
      Return MyBase.Channel.GetIncomingMessageIDsByUserDataSet(session_token)
    End Function

    Public Function GetIncomingMessageDetailByID(ByVal session_token As String, ByVal reply_message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessageDetailByID
      Return MyBase.Channel.GetIncomingMessageDetailByID(session_token, reply_message_id)
    End Function

    Public Function GetIncomingMessageDetailByMessageID(ByVal session_token As String, ByVal message_id As Integer) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessageDetailByMessageID
      Return MyBase.Channel.GetIncomingMessageDetailByMessageID(session_token, message_id)
    End Function

    Public Function GetIncomingMessagesByShortCode(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByShortCode
      Return MyBase.Channel.GetIncomingMessagesByShortCode(session_token, short_code)
    End Function

    Public Function GetIncomingMessagesByKeyword(ByVal session_token As String, ByVal keyword As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByKeyword
      Return MyBase.Channel.GetIncomingMessagesByKeyword(session_token, keyword)
    End Function

    Public Function GetIncomingMessagesForDateRange(ByVal session_token As String, ByVal from_date As Date, ByVal to_Date As Date, ByVal reported As Boolean) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesForDateRange
      Return MyBase.Channel.GetIncomingMessagesForDateRange(session_token, from_date, to_Date, reported)
    End Function

    Public Function GetIncomingMessagesByShortCodeOnce(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByShortCodeOnce
      Return MyBase.Channel.GetIncomingMessagesByShortCodeOnce(session_token, short_code)
    End Function

    Public Function GetIncomingMessagesByShortCodeOnceAdmin(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByShortCodeOnceAdmin
      Return MyBase.Channel.GetIncomingMessagesByShortCodeOnceAdmin(session_token, short_code)
    End Function

    Public Function GetIncomingMessagesByShortCodeAdminAcc(ByVal session_token As String, ByVal short_code As String) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByShortCodeAdminAcc
      Return MyBase.Channel.GetIncomingMessagesByShortCodeAdminAcc(session_token, short_code)
    End Function

    Public Function AutoReplySendAlt(ByVal session_token As String, ByVal reply_message_id As Integer, ByVal status As Boolean) As Boolean Implements CellFind.ServiceSoap.AutoReplySendAlt
      Return MyBase.Channel.AutoReplySendAlt(session_token, reply_message_id, status)
    End Function

    Public Function GetIncomingMessagesByKeywordCount(ByVal session_token As String, ByVal keyword1 As String, ByVal keyword2 As String, ByVal keyword3 As String, ByVal searchOption As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByKeywordCount
      Return MyBase.Channel.GetIncomingMessagesByKeywordCount(session_token, keyword1, keyword2, keyword3, searchOption, from_date, to_Date)
    End Function

    Public Function GetIncomingMessagesByKeywordCountDetail(ByVal session_token As String, ByVal keyword1 As String, ByVal keyword2 As String, ByVal keyword3 As String, ByVal searchOption As String, ByVal from_date As Date, ByVal to_Date As Date) As System.Data.DataSet Implements CellFind.ServiceSoap.GetIncomingMessagesByKeywordCountDetail
      Return MyBase.Channel.GetIncomingMessagesByKeywordCountDetail(session_token, keyword1, keyword2, keyword3, searchOption, from_date, to_Date)
    End Function

    Public Function ExclusionsGetList(ByVal session_token As String) As System.Data.DataSet Implements CellFind.ServiceSoap.ExclusionsGetList
      Return MyBase.Channel.ExclusionsGetList(session_token)
    End Function

    Public Function ExclusionsSearchList(ByVal session_token As String, ByVal recipient_no As String) As System.Data.DataSet Implements CellFind.ServiceSoap.ExclusionsSearchList
      Return MyBase.Channel.ExclusionsSearchList(session_token, recipient_no)
    End Function

    Public Function ExclusionAddToAccount(ByVal session_token As String, ByVal exclude_recipient As String) As Integer Implements CellFind.ServiceSoap.ExclusionAddToAccount
      Return MyBase.Channel.ExclusionAddToAccount(session_token, exclude_recipient)
    End Function

    Public Function ExclusionRemoveFromAccount(ByVal session_token As String, ByVal exclusion_id As Integer) As Integer Implements CellFind.ServiceSoap.ExclusionRemoveFromAccount
      Return MyBase.Channel.ExclusionRemoveFromAccount(session_token, exclusion_id)
    End Function

    Public Function GetCredits(ByVal session_token As String) As Integer Implements CellFind.ServiceSoap.GetCredits
      Return MyBase.Channel.GetCredits(session_token)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function CellFind_ServiceSoap_SendOTASettings(ByVal request As CellFind.SendOTASettingsRequest) As CellFind.SendOTASettingsResponse Implements CellFind.ServiceSoap.SendOTASettings
      Return MyBase.Channel.SendOTASettings(request)
    End Function

    Public Function SendOTASettings(ByVal sessionToken As String, ByVal settings() As CellFind.OTAStruct) As CellFind.OTAStruct()
      Dim inValue As CellFind.SendOTASettingsRequest = New CellFind.SendOTASettingsRequest()
      inValue.sessionToken = sessionToken
      inValue.settings = settings
      Dim retVal As CellFind.SendOTASettingsResponse = CType(Me, CellFind.ServiceSoap).SendOTASettings(inValue)
      Return retVal.SendOTASettingsResult
    End Function
  End Class
End Namespace
