// Generated 22 Jan 2019 09:20 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
  [Serializable]
  public class ROAssessmentDesignationList
   : METTReadOnlyListBase<ROAssessmentDesignationList, ROAssessmentDesignation>
  {
    #region " Business Methods "

    public ROAssessmentDesignation GetItem(int AssessmentDesignationID)
    {
      foreach (ROAssessmentDesignation child in this)
      {
        if (child.AssessmentDesignationID == AssessmentDesignationID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Assessment Designations";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ROAssessmentDesignationList NewROAssessmentDesignationList()
    {
      return new ROAssessmentDesignationList();
    }

    public ROAssessmentDesignationList()
    {
      // must have parameter-less constructor
    }

    public static ROAssessmentDesignationList GetROAssessmentDesignationList()
    {
      return DataPortal.Fetch<ROAssessmentDesignationList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      this.IsReadOnly = false;
      while (sdr.Read())
      {
        this.Add(ROAssessmentDesignation.GetROAssessmentDesignation(sdr));
      }
      this.IsReadOnly = true;
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getROAssessmentDesignationList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}