// Generated 22 Jan 2019 08:52 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
  [Serializable]
  public class ROLanguageList
   : METTReadOnlyListBase<ROLanguageList, ROLanguage>
  {
    #region " Business Methods "

    public ROLanguage GetItem(int LanguageID)
    {
      foreach (ROLanguage child in this)
      {
        if (child.LanguageID == LanguageID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Languages";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ROLanguageList NewROLanguageList()
    {
      return new ROLanguageList();
    }

    public ROLanguageList()
    {
      // must have parameter-less constructor
    }

    public static ROLanguageList GetROLanguageList()
    {
      return DataPortal.Fetch<ROLanguageList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      this.IsReadOnly = false;
      while (sdr.Read())
      {
        this.Add(ROLanguage.GetROLanguage(sdr));
      }
      this.IsReadOnly = true;
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getROLanguageList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}