// Generated 29 Jun 2018 11:42 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
  [Serializable]
  public class ROOrganisationRegionList
   : METTReadOnlyListBase<ROOrganisationRegionList, ROOrganisationRegion>
  {
    #region " Business Methods "

    public ROOrganisationRegion GetItem(int OrganisationRegionID)
    {
      foreach (ROOrganisationRegion child in this)
      {
        if (child.OrganisationRegionID == OrganisationRegionID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Organisation Regions";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ROOrganisationRegionList NewROOrganisationRegionList()
    {
      return new ROOrganisationRegionList();
    }

    public ROOrganisationRegionList()
    {
      // must have parameter-less constructor
    }

    public static ROOrganisationRegionList GetROOrganisationRegionList()
    {
      return DataPortal.Fetch<ROOrganisationRegionList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      this.IsReadOnly = false;
      while (sdr.Read())
      {
        this.Add(ROOrganisationRegion.GetROOrganisationRegion(sdr));
      }
      this.IsReadOnly = true;
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getROOrganisationRegionList";
						cm.Parameters.AddWithValue("@UserID", Singular.Security.Security.CurrentIdentity.UserID);
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}