// Generated 31 Oct 2018 10:35 - Singular Systems Object Generator Version 2.2.693
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROOrganisationTypeList
	 : METTReadOnlyListBase<ROOrganisationTypeList, ROOrganisationType>
	{
		#region " Business Methods "

		public ROOrganisationType GetItem(int OrganisationTypeID)
		{
			foreach (ROOrganisationType child in this)
			{
				if (child.OrganisationTypeID == OrganisationTypeID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "RO Organisationtypes";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static ROOrganisationTypeList NewROOrganisationTypeList()
		{
			return new ROOrganisationTypeList();
		}

		public ROOrganisationTypeList()
		{
			// must have parameter-less constructor
		}

		public static ROOrganisationTypeList GetROOrganisationTypeList()
		{
			return DataPortal.Fetch<ROOrganisationTypeList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROOrganisationType.GetROOrganisationType(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROOrganisationTypeList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}