// Generated 28 May 2018 08:55 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROProvinceList
	 : METTReadOnlyListBase<ROProvinceList, ROProvince>
	{
		#region " Business Methods "

		public ROProvince GetItem(int ProvinceID)
		{
			foreach (ROProvince child in this)
			{
				if (child.ProvinceID == ProvinceID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Provinces";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static ROProvinceList NewROProvinceList()
		{
			return new ROProvinceList();
		}

		public ROProvinceList()
		{
			// must have parameter-less constructor
		}

		public static ROProvinceList GetROProvinceList()
		{
			return DataPortal.Fetch<ROProvinceList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROProvince.GetROProvince(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROProvinceList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}