// Generated 19 Jul 2018 14:53 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROQuestionnaireHomeList
	 : METTReadOnlyListBase<ROQuestionnaireHomeList, ROQuestionnaireHome>
	{
		#region " Business Methods "

		public ROQuestionnaireHome GetItem(int QuestionnaireAnswerSetID)
		{
			foreach (ROQuestionnaireHome child in this)
			{
				if (child.QuestionnaireAnswerSetID == QuestionnaireAnswerSetID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "S";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static ROQuestionnaireHomeList NewROQuestionnaireHomeList()
		{
			return new ROQuestionnaireHomeList();
		}

		public ROQuestionnaireHomeList()
		{
			// must have parameter-less constructor
		}

		public static ROQuestionnaireHomeList GetROQuestionnaireHomeList()
		{
			return DataPortal.Fetch<ROQuestionnaireHomeList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROQuestionnaireHome.GetROQuestionnaireHome(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROQuestionnaireHomeList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}