// Generated 16 Jul 2018 10:27 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROQuestionnaireGroupAnswerResultList
	 : METTReadOnlyListBase<ROQuestionnaireGroupAnswerResultList, ROQuestionnaireGroupAnswerResult>
	{
		#region " Business Methods "

		public ROQuestionnaireGroupAnswerResult GetItem(int QuestionnaireGroupID)
		{
			foreach (ROQuestionnaireGroupAnswerResult child in this)
			{
				if (child.QuestionnaireGroupID == QuestionnaireGroupID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Questionnaire Groups";
		}

		public ROQuestionnaireAnswerResult GetROQuestionnaireAnswerResult(int QuestionnaireAnswerResultID)
		{
			ROQuestionnaireAnswerResult obj = null;
			foreach (ROQuestionnaireGroupAnswerResult parent in this)
			{
				obj = parent.ROQuestionnaireAnswerResultList.GetItem(QuestionnaireAnswerResultID);
				if (obj != null)
				{
					return obj;
				}
			}
			return null;
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public int? QuestionnaireAnswerSetID = null;
			public Criteria(int? QuestionnaireAnswerSetID)
			{
				this.QuestionnaireAnswerSetID = QuestionnaireAnswerSetID;
			}

			public Criteria()
			{
			}

		}

		public static ROQuestionnaireGroupAnswerResultList NewROQuestionnaireGroupAnswerResultList()
		{
			return new ROQuestionnaireGroupAnswerResultList();
		}

		public ROQuestionnaireGroupAnswerResultList()
		{
			// must have parameter-less constructor
		}

		public static ROQuestionnaireGroupAnswerResultList GetROQuestionnaireGroupAnswerResultList()
		{
			return DataPortal.Fetch<ROQuestionnaireGroupAnswerResultList>(new Criteria());
		}

		public static ROQuestionnaireGroupAnswerResultList GetROQuestionnaireGroupAnswerResultList(int? QuestionnaireAnswerSetID)
		{
			return DataPortal.Fetch<ROQuestionnaireGroupAnswerResultList>(new Criteria(QuestionnaireAnswerSetID));
		}


		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROQuestionnaireGroupAnswerResult.GetROQuestionnaireGroupAnswerResult(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;

			ROQuestionnaireGroupAnswerResult parent = null;
			if (sdr.NextResult())
			{
				while (sdr.Read())
				{
					if (parent == null || parent.QuestionnaireGroupID != sdr.GetInt32(1))
					{
						parent = this.GetItem(sdr.GetInt32(1));
					}
					parent.ROQuestionnaireAnswerResultList.RaiseListChangedEvents = false;
					parent.ROQuestionnaireAnswerResultList.Add(ROQuestionnaireAnswerResult.GetROQuestionnaireAnswerResult(sdr));
					parent.ROQuestionnaireAnswerResultList.RaiseListChangedEvents = true;
				}
			}


		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROQuestionnaireGroupAnswerResultList";

						cm.Parameters.AddWithValue("@QuestionnaireAnswerSetID", Singular.Misc.NothingDBNull(crit.QuestionnaireAnswerSetID));


						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}