// Generated 26 Mar 2019 16:02 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROQuestionnaireYearList
	 : METTReadOnlyListBase<ROQuestionnaireYearList, ROQuestionnaireYear>
	{
		#region " Business Methods "

		public ROQuestionnaireYear GetItem(int QuestionnaireYearID)
		{
			foreach (ROQuestionnaireYear child in this)
			{
				if (child.QuestionnaireYearID == QuestionnaireYearID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Questionnaire Years";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static ROQuestionnaireYearList NewROQuestionnaireYearList()
		{
			return new ROQuestionnaireYearList();
		}

		public ROQuestionnaireYearList()
		{
			// must have parameter-less constructor
		}

		public static ROQuestionnaireYearList GetROQuestionnaireYearList()
		{
			return DataPortal.Fetch<ROQuestionnaireYearList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROQuestionnaireYear.GetROQuestionnaireYear(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROQuestionnaireYearList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}