// Generated 03 Jul 2018 08:15 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.Ratings
{
	[Serializable]
	public class RORatingList
	 : METTReadOnlyListBase<RORatingList, RORating>
	{
		#region " Business Methods "

		public RORating GetItem(int RatingID)
		{
			foreach (RORating child in this)
			{
				if (child.RatingID == RatingID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Ratings";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static RORatingList NewRORatingList()
		{
			return new RORatingList();
		}

		public RORatingList()
		{
			// must have parameter-less constructor
		}

		public static RORatingList GetRORatingList()
		{
			return DataPortal.Fetch<RORatingList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(RORating.GetRORating(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getRORatingList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}