// Generated 19 Nov 2018 08:20 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROThreatMatrixScoreList
	 : METTReadOnlyListBase<ROThreatMatrixScoreList, ROThreatMatrixScore>
	{
		#region " Business Methods "

		public ROThreatMatrixScore GetItem(int ThreatMatrixID)
		{
			foreach (ROThreatMatrixScore child in this)
			{
				if (child.ThreatMatrixID == ThreatMatrixID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "R Os";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public Criteria()
			{
			}

		}

		public static ROThreatMatrixScoreList NewROThreatMatrixScoreList()
		{
			return new ROThreatMatrixScoreList();
		}

		public ROThreatMatrixScoreList()
		{
			// must have parameter-less constructor
		}

		public static ROThreatMatrixScoreList GetROThreatMatrixScoreList()
		{
			return DataPortal.Fetch<ROThreatMatrixScoreList>(new Criteria());
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROThreatMatrixScore.GetROThreatMatrixScore(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROThreatMatrixScoreList";
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}