// Generated 03 Aug 2018 12:56 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace METTLib.RO
{
	[Serializable]
	public class ROThreatMatrixList
	 : SingularReadOnlyListBase<ROThreatMatrixList, ROThreatMatrix>
	{
		#region " Business Methods "

		public ROThreatMatrix GetItem(int ItemOneId)
		{
			foreach (ROThreatMatrix child in this)
			{
				if (child.ItemOneId == ItemOneId)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "S";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public int? threatItemID = null;

			public Criteria(int? ThreatItemID)
			{
				this.threatItemID = ThreatItemID;
			}

			public Criteria()
			{
			}

		}

		public static ROThreatMatrixList NewROThreatMatrixList()
		{
			return new ROThreatMatrixList();
		}

		public ROThreatMatrixList()
		{
			// must have parameter-less constructor
		}

		public static ROThreatMatrixList GetROThreatMatrixList()
		{
			return DataPortal.Fetch<ROThreatMatrixList>(new Criteria());
		}

		public static ROThreatMatrixList GetROThreatMatrixList(int? ThreatItemID)
		{
			return DataPortal.Fetch<ROThreatMatrixList>(new Criteria(ThreatItemID));
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROThreatMatrix.GetROThreatMatrix(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROThreatMatrixList";

						cm.Parameters.AddWithValue("@ThreatItemID", Singular.Misc.NothingDBNull(crit.threatItemID));

						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}