'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Singular.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER PROCEDURE InsProcs.insSecurityRole
        '''(
        '''	@SecurityRoleID Int OUTPUT,
        '''	@SectionName VarChar(50),
        '''	@SecurityRole VarChar(50),
        '''	@Description VarChar(100),
        '''	@AutoGeneratedInd Bit = 1
        ''')
        '''AS
        '''
        '''
        '''INSERT INTO SecurityRoles
        '''	(SectionName, SecurityRole, Description, AutoGeneratedInd)
        '''VALUES
        '''	(@SectionName, @SecurityRole, @Description, @AutoGeneratedInd)
        '''
        '''	
        '''SET @SecurityRoleID = SCOPE_IDENTITY()
        '''
        '''RETURN.
        '''</summary>
        Friend ReadOnly Property ALTER_InsSecurityRole() As String
            Get
                Return ResourceManager.GetString("ALTER_InsSecurityRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE [GetProcs].[getTableReferenceList]
        '''(
        '''	@TableToCheck VarChar(40), 
        '''	@Key Int
        ''')
        '''As
        '''
        '''DECLARE @References TABLE (
        '''			TableSchema VarChar(150),
        '''			TableName VarChar(150), 
        '''			ColumnName VarChar(100), 
        '''			ConstraintName VarChar(150), 
        '''			ConstraintDescription VarChar(1024),
        '''			NoOfReferences Int
        ''')
        '''
        '''INSERT INTO @References
        '''SELECT 
        '''		CONVERT(VarChar(150), FK.TABLE_SCHEMA) As TableSchema,
        '''		CONVERT(VarChar(150), FK.TABLE_NAME) As TableName,
        '''		CONVERT(VarChar(100), CU.COLUMN_NAME) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CREATE_GetTableReferences() As String
            Get
                Return ResourceManager.GetString("CREATE_GetTableReferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE InsProcs.insSecurityRole
        '''(
        '''	@SecurityRoleID Int OUTPUT,
        '''	@SectionName VarChar(50),
        '''	@SecurityRole VarChar(50),
        '''	@Description VarChar(100),
        '''	@AutoGeneratedInd Bit = 1
        ''')
        '''AS
        '''
        '''
        '''INSERT INTO SecurityRoles
        '''	(SectionName, SecurityRole, Description, AutoGeneratedInd)
        '''VALUES
        '''	(@SectionName, @SecurityRole, @Description, @AutoGeneratedInd)
        '''
        '''	
        '''SET @SecurityRoleID = SCOPE_IDENTITY()
        '''
        '''RETURN.
        '''</summary>
        Friend ReadOnly Property CREATE_InsSecurityRole() As String
            Get
                Return ResourceManager.GetString("CREATE_InsSecurityRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  SELECT name 
        '''FROM sys.databases 
        '''WHERE name NOT IN 
        '''(
        '''	&apos;master&apos;,
        '''	&apos;tempdb&apos;,
        '''	&apos;model&apos;,
        '''	&apos;msdb&apos;
        ''')
        '''ORDER BY name.
        '''</summary>
        Friend ReadOnly Property GetDatabases() As String
            Get
                Return ResourceManager.GetString("GetDatabases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE [GetProcs].[getDuplicateRecord]
        '''(
        '''	@XmlUniqueProperties xml, 
        '''	@XmlUniqueValues xml, 
        '''	@XmlDisplayProperties xml,
        '''	@PrimaryKeyProperty VarChar(100), 
        '''	@PrimaryKeyValue Int, 
        '''	@TableName VarChar(200)
        ''')
        '''AS
        '''
        '''-- WAITFOR DELAY &apos;00:00:01&apos;
        '''
        '''DECLARE @FieldList VarChar(Max), @CriteriaList VarChar(Max)
        '''
        '''SELECT @FieldList = &apos;&apos;, @CriteriaList = &apos;&apos;
        '''
        '''SELECT @FieldList = @FieldList + ParamValues.Value.value(&apos;.&apos;,&apos;VarChar(100)&apos;) + &apos;, &apos;
        '''FROM @XmlDisplayProperties.nodes(&apos;/Node/Value&apos;) AS Par [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property getDuplicateRecord() As String
            Get
                Return ResourceManager.GetString("getDuplicateRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT SPECIFIC_SCHEMA As [Schema], SPECIFIC_NAME AS ProcName
        '''FROM INFORMATION_SCHEMA.ROUTINES
        '''WHERE LOWER(SPECIFIC_SCHEMA) = LOWER(@SchemaName)
        '''ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME
        '''
        '''SELECT SPECIFIC_SCHEMA As [Schema], SPECIFIC_NAME AS ProcName,
        '''	PARAMETER_NAME As ParameterName, DATA_TYPE As DataType
        '''FROM INFORMATION_SCHEMA.PARAMETERS
        '''WHERE LOWER(SPECIFIC_SCHEMA) = LOWER(@SchemaName)
        '''ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ORDINAL_POSITION.
        '''</summary>
        Friend ReadOnly Property GetStoredProcedures() As String
            Get
                Return ResourceManager.GetString("GetStoredProcedures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @CONTEXT_INFO VarBinary(128)
        '''	SET @CONTEXT_INFO = CONVERT(VarBinary(128), CONVERT(VarBinary(4), @UserID) + CONVERT(VarBinary(2), DB_ID()))
        '''	SET CONTEXT_INFO @CONTEXT_INFO.
        '''</summary>
        Friend ReadOnly Property SetContextInfo() As String
            Get
                Return ResourceManager.GetString("SetContextInfo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
